<?php
/**
 * @file
 * Stanford Sites Personal WYSIWYG functionality
 */
/**
 * Implements hook_form_FORM_ID_alter().
 */
function stanford_personal_wysiwyg_form_wysiwyg_profile_form_alter(&$form, &$form_state, $form_id) {
  $form['css']['css_path']['#maxlength'] = 1024;
  $form['css']['css_path']['#size'] = 120;
}

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */

function stanford_personal_wysiwyg_wysiwyg_editor_settings_alter(&$settings, $context) {
  // add editor CSS to fix overflow issue
  $editor_css = url(drupal_get_path('module', 'stanford_personal_wysiwyg') . '/css/editor.css');
  $settings['contentsCss'][] = $editor_css;
  // find default theme; add CSS for stanford themes
  $theme_default = variable_get('theme_default');
  switch ($theme_default) {
    case 'open_framework' :
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/bootstrap/css/bootstrap.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/css/open_framework.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_framework') . '/css/stanford_framework.css');
      break;
    case 'stanford_basic' :
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_basic') . '/css/stanford_basic.css');
      break;
    case 'stanford_framework' :
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/bootstrap/css/bootstrap.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/css/open_framework.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_framework') . '/css/stanford_framework.css');
      break;
    case 'stanford_branner' :
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/bootstrap/css/bootstrap.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/css/open_framework.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_framework') . '/css/stanford_framework.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_branner') . '/css/stanford_branner.css');
      break;
    case 'stanford_jordan' :
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/bootstrap/css/bootstrap.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/css/open_framework.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_framework') . '/css/stanford_framework.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_jordan') . '/css/stanford_jordan.css');
      break;
    case 'stanford_light' :
      // get our theme settings
      if (module_exists('stanford_personal')) {
        $stanford_light_settings = stanford_personal_get_stanford_light_settings();
        // pull out the styles and fonts for use in the WYSIWYG
        $fonts = $stanford_light_settings['fonts'];
        // commenting out for now - WYSIWYG just loads the body background color, not the background-color for .main
        //$styles = $stanford_light_settings['styles'];
        $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_light') . '/css/' . $fonts . '.css');
        // commenting out for now - WYSIWYG just loads the body background color, not the background-color for .main
        //$settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_light') . '/css/' . $styles . '.css');
      }
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/bootstrap/css/bootstrap.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/css/open_framework.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_light') . '/css/stanford-light.css');
      break;
    case 'stanford_wilbur' :
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/bootstrap/css/bootstrap.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'open_framework') . '/css/open_framework.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_framework') . '/css/stanford_framework.css');
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanford_wilbur') . '/css/stanford_wilbur.css');
      break;
    case 'stanfordmodern' :
      $settings['contentsCss'][] = url(drupal_get_path('theme', 'stanfordmodern') . '/css/stanfordmodern.css');
      break;
  }
}
